LEARNING_RATE : 1e-3
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 128
NUM_EPOCHS : 100
LINEAR_PROBING: False
PROBING_EPOCHS : 50
PATIENCE : 3

IMAGE_SIZE : 224

MODEL: EfficientNetV2S
PRETRAINED: False
LOSS: BCEWithLogitsLoss